---
- name: Install Apache and starts the service
  hosts: webserver
  tasks:

    - name: Install the required package
      ansible.builtin.dnf:
        name: "{{ ansible_facts.ansible_local.custom.general.package }}"
        state: latest

    - name: Start the service
      ansible.builtin.service:
        name: "{{ ansible_facts.ansible_local.custom.general.service }}"
        state: "{{ ansible_facts.ansible_local.custom.general.state }}"

- name: Validate status
  hosts: webserver
  tasks:

    - name: Verificar estado httpd
      ansible.builtin.command: "systemctl status httpd"
      register: statushttpd

    - name: debug statushttpd
      ansible.builtin.debug:
        var: statushttpd
...
